config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    # Redirects signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # localhost:3000/sessions
  devise_for :users
  get 'sessions', to: 'sessions#index'
  get 'sessions/my_session', to: 'sessions#my_session', as: 'my_session'
  get 'sessions/new', to: 'sessions#new'
  get 'sessions/:id', to: 'sessions#show', as: 'session'
  get 'sessions/:id/edit', to: 'sessions#edit', as: 'edit_session'
  
  get 'sessions/:id/link', to: 'sessions#link_session', as: 'link_session'
  patch 'sessions/:id', to: 'sessions#update'
  post 'sessions', to: 'sessions#create'
  delete 'sessions/:id', to: 'sessions#destroy'
  delete 'sessions/:id/link', to: 'sessions#unlink_session', as: 'unlink_session'

  root 'sessions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :session
end

app/models/session.rb
class Session < ApplicationRecord
    belongs_to :user, class_name: "User"
    belongs_to :category
    has_many :user_sessions
    has_many :attendees, through: :user_sessions
    
    validates :title, presence: true
    has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :sessions, class_name: "Session", foreign_key: "user_id", dependent: :destroy
  has_many :user_sessions, foreign_key: "attendee_id"
  has_many :sessions, through: :user_sessions, source: :session
  
  # has_many :user_sessions
  # has_many :sessions, through: :user_sessions
 
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
      return "#{first_name} #{last_name}"
  end
end

app/models/user_session.rb
class UserSession < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization

    # Adding extra fields for signup page
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

    rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
    # Display error message if user is unauthorized to do an actoin
    rescue_from Pundit::NotAuthorizedError, with: :forbidden

    private

    def forbidden
        flash[:alert] = "You are not authorized to perform that action!"
        redirect_to root_path
    end

    def record_not_found
        flash[:alert] = "That session doesnt exist"
        redirect_to root_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # uncomment during development
  # skip_before_action :verify_authenticity_token
  # comment during development
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_auth, only: [:my_session, :new, :create]
  before_action :set_sessions
  before_action :set_session, only: [:show, :update, :edit, :destroy, :link_session, :unlink_session]
  before_action :set_categories
  before_action :check_session, only: [:edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @session = Session.new
  end

  # Grab current_user for their ID and associate ID as FK in session entity
  def create
    @session = Session.create(session_params)
    if @session.valid?
      # Go to show page, flash a session created message
      redirect_to @session, notice: "Session has been created!".html_safe
    else
      # Error message if session doesn't have a title
      flash.now[:alert] = @session.errors.full_messages.join('<br>').html_safe
      render 'new'
    end
  end

  def edit
  end

  def update
    begin
      # Update session entity in DB based on EDIT form params
      @session.update!(session_params)
      # Display new changes
      redirect_to @session
    rescue
      # Error message if sessions doesn't have a title
      flash.now[:alert] = @session.errors.full_messages.join('<br>').html_safe
      render 'edit'
    end
  end

  # Delete session from Session Model
  def destroy
    begin
      @session.destroy
      # Go back to home page
      redirect_to sessions_path
    rescue => error_msg
      redirect_to sessions_path, alert: error_msg
    end
  end

  def my_session
  end

  def link_session
    if !current_user.sessions.exists?(@session.id)
      @session.attendees << current_user
    end
  end

  def unlink_session
    current_user.sessions.where(id: @session.id).destroy
    redirect_to session_path
  end

  private

  def check_auth
    authorize Session
  end

  def check_session
    authorize @session
  end

  # Get all users from DB and order by first name
  def set_users
    @users = User.order(:first_name)
  end
  
  # Get all sessions from DB
  def set_sessions
    @sessions = Session.all
  end

  # Get a specific session from their ID
  def set_session
    @session = Session.find(params[:id])
  end

  # Get all categories from DB and order by name
  def set_categories
    @categories = Category.order(:name)
  end

  # Grab required parameters from the EDIT/CREATE FORMS for POST
  def session_params
    return params.require(:session).permit(:title, :description, :cover, :category_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T2a2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%# Navbar Partial %>
    <%= render partial: "shared/nav"%>

    <main class="p-3">
      <% if notice %>
        <p class="alert alert-info notice" role="alert"><%= notice.html_safe %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger" role="alert"><%= alert.html_safe %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_card.erb
<div class="card m-3 w-25">
  <div class="card-header">
    <h5 class="card-title text-center inline"> <%= link_to session.title, session_path(session.id) %> </h5>
  </div>
  <div class="card-body">
    <p> Host: <%= session.user.full_name %> </p>
    <p> Category: <%= session.category.name %> </p>
    <%= cl_image_tag(session.cover.key, crop: :scale, class: 'w-100', cloud_name: 'meanbojji') if session.cover.attached? %>
    <p> Description: <%= session.description %> </p>
    <% if user_signed_in? %>
      <% if action_name == 'show' %>
        <%= link_to('Attend', link_session_path(session), class: 'btn btn-success') %>
      <% elsif action_name == 'link_session'%>
        <%= link_to('Cancel', unlink_session_path(session), class: 'btn btn-danger', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to cancel '#{session.title}' ?" } }) %>
      <% end %>
    <%end%>
    <% if session.attendees.length > 0 %>
      <% session.attendees.each do |attendee| %>
        <p>Hi I am <%= attendee.full_name %> and I'm attending <%= session.title %> </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
    <%= link_to "Study Session", sessions_path, class: "navbar-brand" %>
    <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "My Sessions", my_session_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
    
    <% if user_signed_in? %>
        <div class="ml-auto btn-toolbar p-3">
            Welcome, <%= current_user.full_name %>!
        </div>
        <div class="ml-auto btn-toolbar">
            <%= button_to 'Logout', destroy_user_session_path, class: 'btn btn-primary', method: :delete, form: { data: { turbo_confirm: "Are you sure you want to log out? " } } %>
        </div>
    <% else %>
        <div class="ml-auto btn-toolbar p-3">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
        </div>
        <div class="ml-auto btn-toolbar">
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
        </div>
    <% end %>
</nav>